[package]
name = "ultra_snake"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
bitflags = "1.3"
lazy_static = "1.4"
derive_more = "0.99"
glam = "0.21"
rand = {version = "0.8", default-features = false, features = ["small_rng"]}