[package]
name = "ultra_crustaceous"
version = "0.1.0"
edition = "2021"

[features]
default = ["rastateur"]

[dependencies]
bitflags = "1.3"
derive_more = "0.99"
rastateur = { path = "../rastateur", optional = true }
